# This allows us to build/run tests using the default setup on our Xcode project
# We can add separate steps for testing twofortyeightTests and twofortyeightUITests

name: Swift_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    -name: Locate
      run: cd mobileapp/twofortyeight.xcodeproj
    
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v

